---
- hosts: dc1
  gather_facts: no

  tasks:
   - include_vars:
       file: "../vars/{{ inventory_hostname }}.yml"
   - name: Generate initial config for dc1
     template:
        src="roles/initial_config/templates/dc1/{{ inventory_hostname }}.j2"
        dest="roles/initial_config/output/{{ inventory_hostname }}.conf"
     delegate_to: 127.0.0.1

# - name: Connect to device and send config
#   connection: local
#   netmiko_install_config:
#     user=admin
#     file={{ inventory_hostname }}.conf
#     log_file=local.log
#     device_type=vyos
#     # update key file config i think
