---
- hosts: local
  gather_facts: no
  remote_user: vyos

  tasks:

    - name: Connect to device and send config
      connection: local
      netmiko_command:
        host_file={'filename':'hosts/hosts.local'}
        user=admin
        password=vyos
        log_file=local.log
        device_type=vyos
        command='show lldp neighbor'
        validation_args={'csv_file':'test.csv'}
        validate_module='parse_checks.vyos.vyos_neighbors.link_checker'
