---
- hosts: local
  gather_facts: no
  remote_user: vyos

  tasks:
  #- name: Generate config locally
  #  template:
  #     src=templates/name-server.j2
  #     dest=output/{{ inventory_hostname }}.conf
  #  delegate_to: 127.0.0.1

    - name: Connect to device and send config
      connection: local
      netmiko_command:
        host_file={'filename':'hosts/hosts.local'}
        user=admin
        log_file=local.log
        device_type=vyos
        key_file='/home/ubuntu/.ssh/id_rsa'
        command='show lldp neighbor'
        validation_args={'csv_file':'test.csv'}
        validate_module='parse_checks.vyos.vyos_neighbors.link_checker'
